# Generated by Django 2.1.7 on 2019-03-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='strategyContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(max_length=500)),
                ('strategy_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='strategyImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_img', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='strategyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_title', models.CharField(max_length=30)),
                ('publish_date', models.DateTimeField(auto_now_add=True, max_length=0)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='strategyimg',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategyInfo'),
        ),
        migrations.AddField(
            model_name='strategycontent',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.strategyInfo'),
        ),
    ]
