# Generated by Django 2.1.7 on 2019-03-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='diaryContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('diary_content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='diaryImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_img', models.CharField(max_length=255)),
                ('diaryContent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diaryContent')),
            ],
        ),
        migrations.CreateModel(
            name='diaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_title', models.CharField(max_length=30)),
                ('publish_date', models.DateTimeField(auto_now_add=True, max_length=0)),
                ('area', models.IntegerField()),
                ('village', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('browse_num', models.IntegerField()),
                ('collect_num', models.IntegerField()),
                ('comment_num', models.IntegerField()),
                ('renovationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.renovationType')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.style')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userInfo')),
            ],
        ),
        migrations.AddField(
            model_name='diarycontent',
            name='diary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.diaryInfo'),
        ),
    ]
