# Generated by Django 2.1.7 on 2019-03-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('designer', '0001_initial'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='caseImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='caseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.IntegerField()),
                ('cost', models.FloatField()),
                ('duration', models.CharField(max_length=30)),
                ('village', models.CharField(max_length=30)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designer.designerInfo')),
                ('houseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.houseType')),
                ('renovationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.renovationType')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.style')),
            ],
        ),
        migrations.CreateModel(
            name='imgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='caseimg',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.caseInfo'),
        ),
        migrations.AddField(
            model_name='caseimg',
            name='imgType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.imgType'),
        ),
    ]
