# Generated by Django 2.1.7 on 2019-03-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericon',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, max_length=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='regist_data',
            field=models.DateTimeField(auto_now_add=True, max_length=0),
        ),
    ]
