# Generated by Django 2.1.7 on 2019-03-31 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500)),
                ('comment_time', models.DateTimeField(auto_now_add=True, max_length=0)),
                ('comment_obj_id', models.IntegerField()),
                ('comment_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='commentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='replyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_content', models.CharField(max_length=500)),
                ('tou_id', models.IntegerField()),
                ('tou_nickname', models.CharField(max_length=30)),
                ('reply_time', models.DateTimeField(auto_now_add=True, max_length=0)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.commentInfo')),
                ('fromu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userInfo')),
                ('reply', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.replyInfo')),
            ],
        ),
        migrations.CreateModel(
            name='replyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='replyinfo',
            name='replyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.replyType'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='commentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.commentType'),
        ),
        migrations.AddField(
            model_name='commentinfo',
            name='fromu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userInfo'),
        ),
    ]
