# Generated by Django 2.1.7 on 2019-03-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20190322_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyinfo',
            name='reply',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.replyInfo'),
        ),
    ]
